[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/create-league"
  to = "/.netlify/functions/create-league"
  status = 200

[[redirects]]
  from = "/api/join-league"
  to = "/.netlify/functions/join-league"
  status = 200
