[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[context.production.environment]
  NEXT_PUBLIC_SITE_URL = "https://itzthepools.com"
  # Supabase PROD keys set in Netlify UI, not in code.

[context.deploy-preview.environment]
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_URL"
  # Supabase DEV keys set in Netlify UI.

[context.branch-deploy.environment]
  NEXT_PUBLIC_SITE_URL = "$DEPLOY_URL"
